טאצ'ים קטנים
Toootim/mastodon pull request #2
Opened 2017-04-23 20:02 UTC by msappir

מגוון שיפורים ושינויים. למשל, דוא"ל זה ראשי תיבות, ואף אחד לא יודע מה זה "יצגן" (גם אני לא) אז זה נקרא תמונת פרופיל עכשיו.
כמו כן אני מקווה שעשיתי את הענף נכון ולא דרסתי שום דבר ולא איבדתי את השינויים של אף אחד, טפו טפו טפו.

2017-04-24 07:31 UTC, seefood requested changes
כמה בקשות הבהרה

2017-04-24 07:31 UTC, seefood commented on app/assets/javascripts/components/locales/he.jsx
> +  "account.follows_you": "במעקב אחריך",
קצת מפחיד.

2017-04-24 07:31 UTC, seefood commented on app/assets/javascripts/components/locales/he.jsx
> +  "privacy.unlisted.long": "לא להצגה בפרהסיה",
ברצינות או בצחוק?

2017-04-24 07:31 UTC, seefood commented on config/locales/devise.he.yml
> +      confirmed: 'כתובת הדוא"ל אומתה בהצלחה.'
לדעתי זה הלחם ולא ראשי תיבות. אישית אני נגד.
In Engish I also write email or eMail, never e-mail.

2017-04-24 07:31 UTC, seefood commented on config/locales/he.yml
> +    error: למרבה הצער, היתה שגיאה בחיפוש החשבון המרוחק
פרהסיה כן אבל מצער לא?

2017-04-24 07:31 UTC, seefood commented on config/locales/he.yml
> +        one: נוסף לך עוקב! סחתיין!
?

2017-04-24 07:31 UTC, seefood commented on config/locales/simple_form.he.yml
> +        avatar: תמונת פרופיל
אז אולי אווטאר?

2017-04-25 07:47 UTC, msappir commented on app/assets/javascripts/components/locales/he.jsx
> +  "privacy.unlisted.long": "לא להצגה בפרהסיה",
ברצינות, אבל אני לא בטוח לגמרי. צריך איזשהו ביטוי לדיבור על הפידים הפומביים וזה נראה לי מתאים (ונראה לי שמופיע בשימוש הזה איפשהו?)
בכל מקרה "לא להצגה בפומבי" נשמע לי לא נכון כי זה כן מוצג בפומבי, פשוט לא בפידים הכלליים...

2017-04-25 07:47 UTC, msappir commented on config/locales/devise.he.yml
> +      confirmed: 'כתובת הדוא"ל אומתה בהצלחה.'
כשראיתי את זה בלי גרשיים בהתחלה לא הצלחתי לקרוא את זה, חשבתי שזה תקלדה.

2017-04-25 07:48 UTC, msappir commented on config/locales/he.yml
> +    error: למרבה הצער, היתה שגיאה בחיפוש החשבון המרוחק
בדקתי וזה פשוט שימוש שגוי ב"למצער", https://www.safa-ivrit.org/milon/lamizar.php
אם זה היה שפת יום יום מילא, אבל שימוש שגוי בנסיון לשפה גבוהה/מליצית זה מכוער בעיניי

2017-04-25 07:48 UTC, msappir commented on config/locales/he.yml
> +        one: נוסף לך עוקב! סחתיין!
מברוכ כותבים עם כ', אבל סחתיין נראה לי יותר טוב אם כבר

2017-04-25 07:49 UTC, msappir commented on config/locales/simple_form.he.yml
> +        avatar: תמונת פרופיל
מה רע בתמונת פרופיל? זה יותר עברי ויותר מובן לדעתי. אווטאר זה מילה יותר גיקית/נישתית.

2017-04-25 07:49 UTC, msappir commented on app/assets/javascripts/components/locales/he.jsx
> +  "account.follows_you": "במעקב אחריך",
כן אבל "בעקיבה" נשמע מוזר ולא טבעי

2017-04-25 12:54 UTC, seefood commented on config/locales/devise.he.yml
> +      confirmed: 'כתובת הדוא"ל אומתה בהצלחה.'
ווקשה! תקלדה היא גם הלחמילה ולא ר"ת.

2017-04-25 12:55 UTC, seefood commented on config/locales/he.yml
> +        one: נוסף לך עוקב! סחתיין!
סלנג הוא סלנג. אז עברנו מ"סחה" ל"מברוכ" ו"סחתיין". אני אעצור את זה כאן ולא אציע מברוכיין

2017-04-25 12:57 UTC, seefood commented on config/locales/simple_form.he.yml
> +        avatar: תמונת פרופיל
תמונה אישית?
ואוואטר היא מילה מסנסקריט, שמזמן מופיעה בכל מקום בווב כבר 15 שנה, לא רק במשחקים. כמו פרופיל היא אינה עברית אבל היא בשימוש נפוץ.

2017-04-25 13:35 UTC, yair commented
I'm sorry, but I'm not going to be the arbiter of every line change in the translation.
Please, at the very least, create a unified PR containing all nine files that I can push to the site for testing, and close these two.
Preferably, it should contain all the strings of v1.2.2, which is what tooot.im runs (Michael noticed that the welcome modal strings are not there), or those in master (as an approximation of the next stable release), but I'm not greedy - any runnable commit will do.

2017-04-25 13:48 UTC, msappir commented
I keep messing things up with the whole branch system here... @seefood, could you please create the unified PR and we'll take it from there? Seems like you have a handle on how this works... Feel free to override my changes you really disagree with, we'll see how it all feels on Toootim later and then we can argue it out again. :)

2017-04-25 13:54 UTC, yair commented
The changes are sufficiently isolated that rebasing the PR to another branch should be trivial, so don't sweat it. Just meant that if you're opening a new one and it's all the same to you, I'd rather have it there.

2017-04-25 14:03 UTC, seefood approved these changes

2017-04-25 14:03 UTC, merged